<?php

namespace Clases\Soportes;

use Clases\Soportes\Soporte;

class Juego extends Soporte
{
    public string $consola;
    private int $minNumJugadores;
    private int $maxNumJugadores;

    public function __construct(string $titulo, int $numero, int $maxNumJugadores, int $minNumJugadores=1, string $consola="PS5", float $precio = 5.00)
    {
        parent::__construct($titulo, $numero, $precio);
        $this->consola=$consola;
        $this->minNumJugadores=$minNumJugadores;
        $this->maxNumJugadores=$maxNumJugadores;
    }

    public function muestraResumen()
    {
        parent::muestraResumen(); // TODO: Change the autogenerated stub
        echo " de la consola $this->consola con un mínimo de $this->minNumJugadores y un máximo de $this->maxNumJugadores";
    }

    public function muestraJugadoresPosibles(){
        $salida = "";
        if ($this->maxNumJugadores===1){
            $salida="Para un jugador";
        }elseif ($this->minNumJugadores==$this->maxNumJugadores){
            $salida="Para $this->minNumJugadores jugadores";
        }else{
            $salida = "De $this->minNumJugadores a $this->maxNumJugadores jugadores";
        }
        echo $salida;
    }
}