<?php

namespace Videoclub;

use Videoclub\Soporte;

class DVD extends Soporte
{
    public string $idiomas;
    private string $formatPantalla;
    public function __construct(string $titulo, int $numero, string $idiomas, string $formatPantalla="16:9", float $precio = 5.00)
    {
        parent::__construct($titulo, $numero, $precio);
        $this->idiomas=$idiomas;
        $this->formatPantalla=$formatPantalla;
    }

    public function muestraResumen()
    {
        parent::muestraResumen(); // TODO: Change the autogenerated stub
        echo " que tiene los idiomas $this->idiomas y un formato de pantalla $this->formatPantalla";
    }

    public function __toString(): string
    {
        $salida = parent::__toString()." que tiene los idiomas $this->idiomas y un formato de pantalla $this->formatPantalla";
        return $salida;
    }


}